#!/bin/bash

TARGET_FOLDER="./configurations"
SERVER_PORT="9888"
SERVER_IP="10.200.200.1/32"
SERVER_INTERFACE="enp0s3"

usage()
{
    echo "Usage: wg-cli [[[-g [client-name]] | [-i] | [-a client-name] | [-c client-name ip mask] | [-h]]"
}

generate_key()
{
    TARGET_KEY_FOLDER=$TARGET_FOLDER/$1/keys
    echo "> Generating a new private and public key for « $1 »"
    mkdir -p $TARGET_KEY_FOLDER
    cd $TARGET_KEY_FOLDER
    umask 077
    wg genkey | tee privatekey | wg pubkey > publickey
    echo "> New key generated in « $TARGET_KEY_FOLDER »"
}

init_server()
{
    PRIVATEKEY="`cat $TARGET_FOLDER/server/keys/privatekey 2>/dev/null`"
    if [ -z "$PRIVATEKEY" ]; then
        echo "⚠️ Please generate a server key before generate the configuration."
        echo "usage: wg-cli -g"
        exit 1
    fi

    echo "> Create a new server configuration"

    echo "[Interface]
PrivateKey = $PRIVATEKEY
Address = $SERVER_IP
ListenPort = $SERVER_PORT
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o $SERVER_INTERFACE -j MASQUERADE; ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -A POSTROUTING -o $SERVER_INTERFACE -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o $SERVER_INTERFACE -j MASQUERADE; ip6tables -D FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -D POSTROUTING -o $SERVER_INTERFACE -j MASQUERADE
" > $TARGET_FOLDER/server/wg0.conf

    echo ""
    echo "If you want Internet shared with your client, don't forget to enable ipv4 forwarding."
    echo "vim /etc/systctl.conf"
    echo "# and then"
    echo "sysctl -p"
    echo ""
}

create_client()
{
    echo "> Create a new client configuration for « $1 »"
}

add_client()
{
    echo "> Add client « $1 » to the server configuration"
}

while [ "$1" != "" ]; do
    case $1 in
        -g | --generate-key )   shift
                                if [ -z "$1" ]; then
                                    generate_key "server"
                                else
                                    generate_key "clients/$1"
                                fi
                                exit
                                ;;
        -i | --init-server )    shift
                                init_server
                                exit
                                ;;
        -c | --create-client )  shift
                                create_client
                                exit
                                ;;
        -a | --add-client )     shift
                                add_client
                                exit
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done